added js conf and tech unite logo
thisdot/framework.dev pull request #470
Opened 2022-11-16 13:05 UTC by aksy2512

This fix resolves #454 
The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
I have verified the fix works and introduces no further errors

Screenshot of the change - 
![image](https://user-images.githubusercontent.com/79045568/202188255-8faba246-aa26-44c8-b98a-030e70af3a8f.png)

2022-11-16 15:15 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-11-16 15:15 UTC, jdwilkin4 commented on packages/site/src/data/angular/communities.ts
> +	        "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITERUTDxAWFRAXGBcYFRUQEBUVDhIWFxcYGBUSFhUYHiggGRolGxYXIT0hJSorLi4uFx8zOzMsOCgtLisBCgoKDg0OGxAQGi0lHyUtLS0tLS0vLS0tLS0tLS0tLS0tLS
This image url is to long. 
Let's try something shorter like this one
```suggestion
	        "https://pbs.twimg.com/profile_images/1548041354806059008/CfEL7qut_400x400.jpg",   
```

2022-11-16 15:15 UTC, jdwilkin4 commented on packages/site/src/data/react/communities.ts
> +	        "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITERUTDxAWFRAXGBcYFRUQEBUVDhIWFxcYGBUSFhUYHiggGRolGxYXIT0hJSorLi4uFx8zOzMsOCgtLisBCgoKDg0OGxAQGi0lHyUtLS0tLS0vLS0tLS0tLS0tLS0tLS
Let's use this short image url instead
```suggestion
	        "https://pbs.twimg.com/profile_images/1548041354806059008/CfEL7qut_400x400.jpg",   
```

2022-11-16 15:15 UTC, jdwilkin4 commented on packages/site/src/data/vue/communities.ts
> +	        "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITERUTDxAWFRAXGBcYFRUQEBUVDhIWFxcYGBUSFhUYHiggGRolGxYXIT0hJSorLi4uFx8zOzMsOCgtLisBCgoKDg0OGxAQGi0lHyUtLS0tLS0vLS0tLS0tLS0tLS0tLS
```suggestion
	        "https://pbs.twimg.com/profile_images/1548041354806059008/CfEL7qut_400x400.jpg",   
```

2022-11-22 17:56 UTC, jdwilkin4 commented
@aksy2512 

Are you still interested in working on this?

2022-11-22 18:01 UTC, aksy2512 commented
@jdwilkin4 I am facing some error while rebasing pushing. Should I create a new Pull request?

2022-11-22 18:07 UTC, jdwilkin4 commented
@aksy2512 

In this situation, you don't have to make these changes locally because these are all minor content changes for the image. 
So you can use the suggestion tool and click on Commit suggestion

<img width="931" alt="Screen Shot 2022-11-22 at 10 07 00 AM" src="https://user-images.githubusercontent.com/67210629/203389026-20987442-3ab2-4e67-916e-326ba95a800d.png">

2022-11-22 18:26 UTC, jdwilkin4 commented
@aksy2512 

Don't forget to address all of the review comments so we can merge your PR 👍

2022-11-22 18:28 UTC, aksy2512 commented
@jdwilkin4 How can I add the review comments now? Please help

2022-11-22 18:42 UTC, jdwilkin4 commented
@aksy2512 

It looks like you already made the necessary changes to one of my review comments because I can see this commit you made here
<img width="892" alt="Screen Shot 2022-11-22 at 10 38 16 AM" src="https://user-images.githubusercontent.com/67210629/203394822-d98eeb1d-90a9-415d-ad0b-e8afaed51d67.png">

But you should also see these comments here

<img width="787" alt="Screen Shot 2022-11-22 at 10 41 19 AM" src="https://user-images.githubusercontent.com/67210629/203395392-68ef9ca9-6dda-4579-a8c9-e825bc2190f9.png">

and here
<img width="819" alt="Screen Shot 2022-11-22 at 10 41 37 AM" src="https://user-images.githubusercontent.com/67210629/203395441-17e6bd3e-66dc-4e5c-8cac-798bd32c5f3b.png">

I need to click on the Commit suggestion buttons for those two remaining images and then we can merge your PR.

2022-11-22 19:10 UTC, jdwilkin4 commented
@aksy2512 

Thank you for making those changes.
As I was testing it, I discovered that the tech unit Africa image has its URL signature expire. 
I went ahead and pushed an update to replace that image with a new. 

We should be good now to merge this PR 👍

2022-11-22 19:14 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-11-22 19:14 UTC, merged