Add Deno libraries
thisdot/framework.dev pull request #517
Opened 2022-12-01 02:28 UTC by tvanantwerp

## Type of change

- [X] Content addition
- [ ] Bug fix
- [ ] Behavior change

## Summary of change

Add list of popular Deno libraries.

## Checklist

- [X] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [X] I have searched all existing content and verified my additions are novel
      and unique
- [X] The content was added to the end of the appropriate data list
- [ ] All required content fields are accurately populated
- [ ] All items are tagged with all relevant tags

2022-12-01 13:48 UTC, vyktoremario reviewed
Change all `https://github.com` to `https://www.github.com/`

This is because the LibraryCard (`packages/system/src/components/cards/library-card.tsx`) component has a logic that tries to get the star count based on the repoName and in its logic, it is replacing `https://www.github.com/` with an empty string to have access to the repoName. This does not work for the libraries on this file, hence it returns `404 Badge not found`

2022-12-01 14:34 UTC, tvanantwerp commented
> Change all `https://github.com` to `https://www.github.com/`
> 
> This is because the LibraryCard (`packages/system/src/components/cards/library-card.tsx`) component has a logic that tries to get the star count based on the repoName and in its logic, it is replacing `https://www.github.com/` with an empty string to have access to the repoName. This does not work for the libraries on this file, hence it returns `404 Badge not found`

@vyktoremario I don't think we should care if the `www` is in the GitHub URL or not, so I modified the library card to check for GitHub links with or without it.

2022-12-02 15:35 UTC, vyktoremario approved these changes

2022-12-02 15:45 UTC, tyrelchambers requested changes

2022-12-02 15:45 UTC, tyrelchambers commented on packages/site/src/data/deno/libraries.ts
> +		author: "",
Do we have an author for this package?

2022-12-02 15:53 UTC, tyrelchambers approved these changes

2022-12-02 15:55 UTC, merged