My branch
thisdot/framework.dev pull request #519
Opened 2022-12-01 16:49 UTC by aksy2512

## Type of change
- [ ] This change resolves #481
- [ ] I have confirmed with a maintainer that this change is desired and been
      given the go-ahead to work on it in the relevant issue discussion
- [ ] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [ ] I have verified the change and the rest of the site works as expected
- [ ] If the change introduces new components, these have been added to
     `packages\system\src\components\homepage\homepage.tsx` with a `.homepage.tsx` file that
      adequately renders possible variations of each component.

Problem - I have used fetch,  Useeffect and Usestate but it is not working. Please have a look at it

2022-12-01 19:28 UTC, jdwilkin4 requested changes
I played around with this and was able to get it working. 
You can delete what you have in the `homepage.tsx`. And you can use this instead. 

In the `index.astro` file, that is where you can fetch the data. 
```js
interface ContributorAvatars {
		avatar_url: string
		[id: string]: string
	}

const data =
		await fetch(
			"https://api.github.com/repos/thisdot/framework.dev/contributors?anon=1"
		)
			.then((res) => res.json())
			.then((data: ContributorAvatars[]) => data.map((user) => user.avatar_url))
```
We can pass this `data` into a prop for the homepage component. 
You will need to update the homepage component to accept this prop. 

As for styles, I am waiting to here back from the project manager on the exact design he is looking for. 
I will post the approved design on the ticket. 

Hope that helps! 👍

2022-12-01 19:28 UTC, jdwilkin4 commented on packages/site/src/data/vue/communities.ts
> +		image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAABI1BMVEUMDAz///8BvXAAAAACvW78/PwLDAwCvHGPj48OCw4HAAANDQocr24WSS8ACAMKDQz5/////voPqW0Eumn1//+z59gSuHLu7u4AwG//+/+Dyq8eHh4
Please remove this because you already committed these changes in your last PR.

Make sure to merge the latest changes from `main`.

2022-12-01 19:28 UTC, jdwilkin4 commented on packages/site/src/data/vue/communities.ts
> +			"https://tinyurl.com/ufuj2rv4",
Please remove this because you already committed these changes in your last PR.

Make sure to merge the latest changes from main.

2022-12-05 21:52 UTC, aksy2512 commented
> I played around with this and was able to get it working. You can delete what you have in the `homepage.tsx`. And you can use this instead.
> 
> In the `index.astro` file, that is where you can fetch the data.
> 
> ```js
> interface ContributorAvatars {
> 		avatar_url: string
> 		[id: string]: string
> 	}
> 
> const data =
> 		await fetch(
> 			"https://api.github.com/repos/thisdot/framework.dev/contributors?anon=1"
> 		)
> 			.then((res) => res.json())
> 			.then((data: ContributorAvatars[]) => data.map((user) => user.avatar_url))
> ```
> 
> We can pass this `data` into a prop for the homepage component. You will need to update the homepage component to accept this prop.
> 
> As for styles, I am waiting to here back from the project manager on the exact design he is looking for. I will post the approved design on the ticket.
> 
> Hope that helps! 👍

I am not able to find the index.astro file. Please help me

2022-12-05 23:05 UTC, jdwilkin4 commented
@aksy2512 

The `index.astro` file is under the `packages/site/src/pages` directory

Here is a link to the file
https://github.com/thisdot/framework.dev/blob/main/packages/site/src/pages/index.astro

2022-12-10 13:04 UTC, aksy2512 commented
@jdwilkin4 Can you please tell me how to pass the data from index.astro to homepage.tsx using props since I am facing errors

2022-12-10 19:21 UTC, jdwilkin4 commented
@aksy2512 

It would help to see your code to see the errors.
I would suggest pushing up your changes s owe can see your code.

You can also look at the react docs on how to pass props to a component 
https://beta.reactjs.org/learn/passing-props-to-a-component

2022-12-10 20:41 UTC, aksy2512 commented
> 

Actually, The issue I was facing was that I wasn't able to import anything from the index.astro file in our homepage.tsx file

2022-12-10 21:27 UTC, jdwilkin4 commented
If you are still experiencing issue, I would still suggest pushing up your code so we can see the issue for ourselves and help you from there.

2022-12-11 00:42 UTC, closed without merging