Feat/618 various updates
thisdot/framework.dev pull request #631
Opened 2023-01-17 22:35 UTC by morgnism

## Type of change

- [ ] Content addition
- [ ] Bug fix
- [ ] Behavior change

## Summary of change

## Checklist

- [ ] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [ ] I have searched all existing content and verified my additions are novel
      and unique
- [ ] The content was added to the end of the appropriate data list
- [ ] All required content fields are accurately populated
- [ ] All items are tagged with all relevant tags

2023-01-17 22:54 UTC, jdwilkin4 commented
When I running it locally, I noticed a broken image for Feathers.
<img width="513" alt="Screenshot 2023-01-17 at 2 54 22 PM" src="https://user-images.githubusercontent.com/67210629/213029964-62f3db6d-2d54-4b90-8b3e-2220a40bacdc.png">

We could throw in that fix into this PR since this is a general cleanup PR

2023-01-17 23:01 UTC, jdwilkin4 requested changes
I think it looks good. 
It was just those two broken image links that needed replacing 👍

2023-01-18 15:57 UTC, lindakatcodes requested changes
Found a few things, but I'd think they should be fairly quick to address:
- Some duplicated tags in the libraries file, I pointed out which ones - just needs the duplicate removed
- Correction in the library-tag model I think should be changed per the ticket

Everything else looks good! And I see State of Node is already there, so that's good. :)

2023-01-18 15:57 UTC, lindakatcodes commented on packages/site/src/data/nodejs/libraries.ts
> +		tags: [LibraryTag.FRAMEWORKS, LibraryTag.FRAMEWORKS],
This creates 2 tags for frameworks - we should only need the one I'd think?

2023-01-18 15:57 UTC, lindakatcodes commented on packages/site/src/data/nodejs/libraries.ts
> +		tags: [LibraryTag.FRAMEWORKS, LibraryTag.FRAMEWORKS],
Duplicate tag

2023-01-18 15:57 UTC, lindakatcodes commented on packages/site/src/data/nodejs/libraries.ts
> +		tags: [LibraryTag.FRAMEWORKS, LibraryTag.UTILITIES, LibraryTag.FRAMEWORKS],
Duplicate tag for framework

2023-01-18 15:57 UTC, lindakatcodes commented on packages/system/src/models/library-tag.ts
> +	SERVERLESS = "serverless",
Shouldn't this be "serverless framework", per the ticket?

2023-01-18 16:20 UTC, jdwilkin4 approved these changes
Looks good 👍

2023-01-18 16:29 UTC, lindakatcodes commented on packages/system/src/models/library-tag.ts
> +	SERVERLESS = "serverless",
So do we need this addition here at all then? If it's new from this PR and we're not using it - should it be removed completely?

2023-01-18 16:40 UTC, lindakatcodes approved these changes

2023-01-19 14:00 UTC, merged